import { CharacterClassType, Ability } from '../types/game';

export interface ClassDefinition {
  type: CharacterClassType;
  name: string;
  title: string;
  description: string;
  color: string;
  themeGlow: string;
  baseHp: number;
  baseMp: number;
  baseSpeed: number;
  baseAttack: number;
  baseCrit: number;
  abilities: Ability[];
  passiveText: string;
}

export const CLASS_DEFINITIONS: Record<CharacterClassType, ClassDefinition> = {
  warrior: {
    type: 'warrior',
    name: 'Warrior',
    title: 'Vanguard of Iron',
    description: 'Master of heavy armor, close-quarters cleaves, and ground-shaking crowd control.',
    color: '#ef4444',
    themeGlow: 'rgba(239, 68, 68, 0.4)',
    baseHp: 420,
    baseMp: 120,
    baseSpeed: 4.8,
    baseAttack: 28,
    baseCrit: 0.1,
    passiveText: 'Blood & Iron: Gain 1.5% attack damage per 5% missing HP.',
    abilities: [
      {
        id: 'w_cleave',
        name: 'Heavy Cleave',
        description: 'Swings greatsword in a 120° frontal arc, slashing all enemies.',
        icon: '⚔️',
        key: '1',
        manaCost: 15,
        cooldown: 1.2,
        currentCooldown: 0,
        castTime: 0,
        range: 110,
        type: 'damage',
        aoeRadius: 100,
        damageMultiplier: 1.6,
        effectColor: '#ef4444',
        sound: 'slash',
      },
      {
        id: 'w_whirlwind',
        name: 'Whirlwind',
        description: 'Spins violently, dealing 360° damage and boosting speed by 25% for 2s.',
        icon: '🌪️',
        key: '2',
        manaCost: 30,
        cooldown: 4.0,
        currentCooldown: 0,
        castTime: 0,
        range: 130,
        type: 'aoe',
        aoeRadius: 130,
        damageMultiplier: 2.2,
        effectColor: '#f97316',
        sound: 'burst',
      },
      {
        id: 'w_iron_roar',
        name: 'Iron Fortitude',
        description: 'Emits a battle cry that grants a 120 HP shield and 40% armor for 5s.',
        icon: '🛡️',
        key: '3',
        manaCost: 25,
        cooldown: 8.0,
        currentCooldown: 0,
        castTime: 0,
        range: 0,
        type: 'buff',
        healAmount: 120,
        effectColor: '#eab308',
        sound: 'heal',
      },
      {
        id: 'w_earthshaker',
        name: 'Earthshaker Slam',
        description: 'Leaps and smashes the earth, stunning enemies and dealing immense crater damage.',
        icon: '💥',
        key: '4',
        manaCost: 50,
        cooldown: 12.0,
        currentCooldown: 0,
        castTime: 0.3,
        range: 260,
        type: 'damage',
        aoeRadius: 160,
        damageMultiplier: 4.0,
        effectColor: '#dc2626',
        sound: 'slam',
      },
    ],
  },
  mage: {
    type: 'mage',
    name: 'Mage',
    title: 'Archmage of the Arcane',
    description: 'Wields destructive elemental fires, icy crowd control, and celestial meteor strikes.',
    color: '#a855f7',
    themeGlow: 'rgba(168, 85, 247, 0.4)',
    baseHp: 240,
    baseMp: 350,
    baseSpeed: 4.5,
    baseAttack: 38,
    baseCrit: 0.15,
    passiveText: 'Arcane Surge: Regenerates 4% maximum mana per second while out of combat.',
    abilities: [
      {
        id: 'm_fireball',
        name: 'Fireball',
        description: 'Hurls an explosive sphere of fire that detonates on impact.',
        icon: '🔥',
        key: '1',
        manaCost: 20,
        cooldown: 0.8,
        currentCooldown: 0,
        castTime: 0,
        range: 480,
        type: 'damage',
        aoeRadius: 70,
        damageMultiplier: 1.8,
        effectColor: '#f97316',
        sound: 'fire',
      },
      {
        id: 'm_frost_nova',
        name: 'Frost Nova',
        description: 'Freezes all nearby enemies in place, dealing ice damage and slowing them by 60%.',
        icon: '❄️',
        key: '2',
        manaCost: 35,
        cooldown: 5.0,
        currentCooldown: 0,
        castTime: 0,
        range: 160,
        type: 'aoe',
        aoeRadius: 160,
        damageMultiplier: 2.0,
        effectColor: '#38bdf8',
        sound: 'ice',
      },
      {
        id: 'm_blink',
        name: 'Arcane Blink',
        description: 'Instantly teleports 240 units forward towards the cursor.',
        icon: '✨',
        key: '3',
        manaCost: 30,
        cooldown: 6.0,
        currentCooldown: 0,
        castTime: 0,
        range: 240,
        type: 'teleport',
        effectColor: '#c084fc',
        sound: 'blink',
      },
      {
        id: 'm_meteor',
        name: 'Cataclysm Meteor',
        description: 'Calls down a colossal meteor from the heavens, incinerating everything in the blast radius.',
        icon: '☄️',
        key: '4',
        manaCost: 65,
        cooldown: 14.0,
        currentCooldown: 0,
        castTime: 0.6,
        range: 420,
        type: 'aoe',
        aoeRadius: 220,
        damageMultiplier: 5.5,
        effectColor: '#ea580c',
        sound: 'meteor',
      },
    ],
  },
  ranger: {
    type: 'ranger',
    name: 'Ranger',
    title: 'Shadow Archer',
    description: 'Swift marksman delivering rapid piercing arrows, poisonous traps, and hail storms.',
    color: '#22c55e',
    themeGlow: 'rgba(34, 197, 94, 0.4)',
    baseHp: 300,
    baseMp: 180,
    baseSpeed: 5.4,
    baseAttack: 32,
    baseCrit: 0.25,
    passiveText: 'Eagle Eye: +15% Critical Strike multiplier and +80 attack range.',
    abilities: [
      {
        id: 'r_multishot',
        name: 'Triple Arrow',
        description: 'Fires 3 piercing enchanted arrows in a forward cone.',
        icon: '🏹',
        key: '1',
        manaCost: 15,
        cooldown: 1.0,
        currentCooldown: 0,
        castTime: 0,
        range: 520,
        type: 'damage',
        damageMultiplier: 1.5,
        effectColor: '#4ade80',
        sound: 'arrow',
      },
      {
        id: 'r_poison_trap',
        name: 'Toxic Trap',
        description: 'Lays a poison trap that explodes when enemies step near, dealing poison DoT.',
        icon: '🧪',
        key: '2',
        manaCost: 25,
        cooldown: 4.5,
        currentCooldown: 0,
        castTime: 0,
        range: 200,
        type: 'aoe',
        aoeRadius: 120,
        damageMultiplier: 2.4,
        effectColor: '#84cc16',
        sound: 'burst',
      },
      {
        id: 'r_windrunner',
        name: 'Windrunner Focus',
        description: 'Surges with agility, boosting movement speed by 40% and crit chance by 30% for 4s.',
        icon: '🍃',
        key: '3',
        manaCost: 20,
        cooldown: 7.0,
        currentCooldown: 0,
        castTime: 0,
        range: 0,
        type: 'buff',
        effectColor: '#10b981',
        sound: 'dash',
      },
      {
        id: 'r_arrow_storm',
        name: 'Arrow Barrage',
        description: 'Showers target area with hundreds of deadly arrows over 2.5 seconds.',
        icon: '🎯',
        key: '4',
        manaCost: 55,
        cooldown: 13.0,
        currentCooldown: 0,
        castTime: 0.4,
        range: 460,
        type: 'aoe',
        aoeRadius: 190,
        damageMultiplier: 4.8,
        effectColor: '#22c55e',
        sound: 'burst',
      },
    ],
  },
  paladin: {
    type: 'paladin',
    name: 'Paladin',
    title: 'Guardian of Dawn',
    description: 'Radiant holy knight capable of massive sustained durability and healing bursts.',
    color: '#eab308',
    themeGlow: 'rgba(234, 179, 8, 0.4)',
    baseHp: 460,
    baseMp: 220,
    baseSpeed: 4.7,
    baseAttack: 26,
    baseCrit: 0.1,
    passiveText: 'Divine Grace: Whenever you drop below 30% HP, instantly restore 15% Max HP (60s CD).',
    abilities: [
      {
        id: 'p_holy_strike',
        name: 'Radiant Smite',
        description: 'Strikes target with blazing divine energy, dealing holy damage.',
        icon: '⚡',
        key: '1',
        manaCost: 15,
        cooldown: 1.0,
        currentCooldown: 0,
        castTime: 0,
        range: 120,
        type: 'damage',
        damageMultiplier: 1.7,
        effectColor: '#facc15',
        sound: 'holy',
      },
      {
        id: 'p_divine_heal',
        name: 'Holy Radiance',
        description: 'Restores 140 HP to yourself and nearby players, plus damages undead.',
        icon: '💖',
        key: '2',
        manaCost: 40,
        cooldown: 5.5,
        currentCooldown: 0,
        castTime: 0,
        range: 160,
        type: 'heal',
        healAmount: 140,
        aoeRadius: 160,
        effectColor: '#fef08a',
        sound: 'heal',
      },
      {
        id: 'p_hammer',
        name: 'Judgement Hammer',
        description: 'Hurls a spinning golden hammer that deals damage and stuns for 1.2s.',
        icon: '🔨',
        key: '3',
        manaCost: 30,
        cooldown: 7.0,
        currentCooldown: 0,
        castTime: 0,
        range: 360,
        type: 'damage',
        damageMultiplier: 2.5,
        effectColor: '#f59e0b',
        sound: 'holy',
      },
      {
        id: 'p_aegis',
        name: 'Sunlight Sanctuary',
        description: 'Creates a sacred sanctuary circle for 6s that reduces damage taken by 60% and heals over time.',
        icon: '☀️',
        key: '4',
        manaCost: 60,
        cooldown: 15.0,
        currentCooldown: 0,
        castTime: 0.3,
        range: 0,
        type: 'buff',
        aoeRadius: 180,
        healAmount: 220,
        effectColor: '#fef08a',
        sound: 'heal',
      },
    ],
  },
};
